import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

 
export const metadata: Metadata = {
  title: "ZeroCross — Safe Food, Global Flavors",
  description: "Discover gluten-free and nut-free production spaces, groceries, and recipes from cuisines around the world.",
};
 
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className="min-h-full flex flex-col bg-[var(--icyblue)] text-[var(--navy)]">
        <Navbar />
        <main className="flex-1 page-shell">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
 
// Old code from last week
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">
//         <Navbar />
//         {children}
//         <Footer />
//         </body>
//     </html>
//   );
// }
