/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddplaceRouteImport } from './routes/addplace'
import { Route as ChefCardRouteImport } from './routes/chef-card'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EditprofileRouteImport } from './routes/editprofile'
import { Route as MenuanalyzerRouteImport } from './routes/menuanalyzer'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthSigninRouteImport } from './routes/auth.signin'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as PlacesIndexRouteImport } from './routes/places.index'
import { Route as PlacesIdRouteImport } from './routes/places.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddplaceRoute = AddplaceRouteImport.update({
  id: '/addplace',
  path: '/addplace',
  getParentRoute: () => rootRouteImport,
} as any)
const ChefCardRoute = ChefCardRouteImport.update({
  id: '/chef-card',
  path: '/chef-card',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EditprofileRoute = EditprofileRouteImport.update({
  id: '/editprofile',
  path: '/editprofile',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuanalyzerRoute = MenuanalyzerRouteImport.update({
  id: '/menuanalyzer',
  path: '/menuanalyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesIndexRoute = PlacesIndexRouteImport.update({
  id: '/places/',
  path: '/places/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesIdRoute = PlacesIdRouteImport.update({
  id: '/places/$id',
  path: '/places/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/addplace': typeof AddplaceRoute
  '/chef-card': typeof ChefCardRoute
  '/dashboard': typeof DashboardRoute
  '/editprofile': typeof EditprofileRoute
  '/menuanalyzer': typeof MenuanalyzerRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/places/$id': typeof PlacesIdRoute
  '/places/': typeof PlacesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/addplace': typeof AddplaceRoute
  '/chef-card': typeof ChefCardRoute
  '/dashboard': typeof DashboardRoute
  '/editprofile': typeof EditprofileRoute
  '/menuanalyzer': typeof MenuanalyzerRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/places/$id': typeof PlacesIdRoute
  '/places': typeof PlacesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/addplace': typeof AddplaceRoute
  '/chef-card': typeof ChefCardRoute
  '/dashboard': typeof DashboardRoute
  '/editprofile': typeof EditprofileRoute
  '/menuanalyzer': typeof MenuanalyzerRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/places/$id': typeof PlacesIdRoute
  '/places/': typeof PlacesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/addplace'
    | '/chef-card'
    | '/dashboard'
    | '/editprofile'
    | '/menuanalyzer'
    | '/onboarding'
    | '/reset-password'
    | '/auth/forgot-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/places/$id'
    | '/places/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/addplace'
    | '/chef-card'
    | '/dashboard'
    | '/editprofile'
    | '/menuanalyzer'
    | '/onboarding'
    | '/reset-password'
    | '/auth/forgot-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/places/$id'
    | '/places'
  id:
    | '__root__'
    | '/'
    | '/addplace'
    | '/chef-card'
    | '/dashboard'
    | '/editprofile'
    | '/menuanalyzer'
    | '/onboarding'
    | '/reset-password'
    | '/auth/forgot-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/places/$id'
    | '/places/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddplaceRoute: typeof AddplaceRoute
  ChefCardRoute: typeof ChefCardRoute
  DashboardRoute: typeof DashboardRoute
  EditprofileRoute: typeof EditprofileRoute
  MenuanalyzerRoute: typeof MenuanalyzerRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  PlacesIdRoute: typeof PlacesIdRoute
  PlacesIndexRoute: typeof PlacesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addplace': {
      id: '/addplace'
      path: '/addplace'
      fullPath: '/addplace'
      preLoaderRoute: typeof AddplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chef-card': {
      id: '/chef-card'
      path: '/chef-card'
      fullPath: '/chef-card'
      preLoaderRoute: typeof ChefCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editprofile': {
      id: '/editprofile'
      path: '/editprofile'
      fullPath: '/editprofile'
      preLoaderRoute: typeof EditprofileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menuanalyzer': {
      id: '/menuanalyzer'
      path: '/menuanalyzer'
      fullPath: '/menuanalyzer'
      preLoaderRoute: typeof MenuanalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places/': {
      id: '/places/'
      path: '/places'
      fullPath: '/places/'
      preLoaderRoute: typeof PlacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places/$id': {
      id: '/places/$id'
      path: '/places/$id'
      fullPath: '/places/$id'
      preLoaderRoute: typeof PlacesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddplaceRoute: AddplaceRoute,
  ChefCardRoute: ChefCardRoute,
  DashboardRoute: DashboardRoute,
  EditprofileRoute: EditprofileRoute,
  MenuanalyzerRoute: MenuanalyzerRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  PlacesIdRoute: PlacesIdRoute,
  PlacesIndexRoute: PlacesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
